config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get "/ping", to: "base#ping"
        resources :check_reports, path: "check-reports", only: [:create]
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "sessions#new"

  post "sign_up", to: "accounts#create"
  get "sign_up", to: "accounts#new"

  put "account", to: "accounts#update"
  get "account", to: "accounts#edit"
  delete "account", to: "accounts#destroy"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

  resources :checks
  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<h1>Rails Authentication From Scratch</h1>
<ul>
  <% if user_signed_in? %>
    <li><%= link_to "My Acount", account_path %></li>
      <li><%= button_to "Logout", logout_path, method: :delete %></li>
  <% else %>
      <li><%= link_to "Login", login_path %></li>
      <li><%= link_to "Sign Up", sign_up_path %></li>
      <li><%= link_to "Forgot my password", new_password_path %></li>
      <li><%= link_to "Didn't receive confirmation instructions", new_confirmation_path %></li>
  <% end %>
</ul>