config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get "/ping", to: "base#ping"
        resources :check_reports, path: "check-reports", only: [:create]
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "sessions#new"

  post "sign_up", to: "accounts#create"
  get "sign_up", to: "accounts#new"

  put "account", to: "accounts#update"
  get "account", to: "accounts#edit"
  delete "account", to: "accounts#destroy"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

  resources :checks
  resources :users
end

app/models/check.rb
class Check < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :hostname
end

app/controllers/checks_controller.rb
class ChecksController < AuthenticatedController
  before_action :set_check, only: %i[show edit update destroy]

  # GET /checks or /checks.json
  def index
    # @search = Check.ransack(params[:q])
    # @checks = @search.result
    @checks = Check.order(date: :desc, hostname: :asc, name: :asc).page params[:page]
  end

  # GET /checks/1
  def show
  end

  # GET /checks/new
  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
  end

  # POST /checks
  def create
    @check = Check.new(check_params)

    if @check.save
      redirect_to check_url(@check), notice: "Check was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /checks/1
  def update
    if @check.update(check_params)
      redirect_to check_url(@check), notice: "Check was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /checks/1
  def destroy
    @check.destroy

    redirect_to checks_url, notice: "Check was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_check
    @check = Check.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def check_params
    params.require(:check).permit(:name, :description, :hostname)
  end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_check.html.erb
<div id="<%= dom_id check %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= check.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= check.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hostname:</strong>
    <%= check.hostname %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this check", check, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this check', edit_check_path(check), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/checks/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Checks</h1>
  </div>

  <div id="checks" class="min-w-full px-4 py-8 sm:px-0">

    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <% if @checks.present? %>
          <!-- BEGIN Table -->
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Hostname
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Description
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Date
                  </th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @checks.each do |check| %>
                  <tr class="<%= cycle("bg-white", "bg-gray-50") %>">
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      <%= check.hostname %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <%= check.name %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <%= truncate check.description, length: 60 %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <%= check.date %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <%= link_to "Show", check, class: "text-indigo-600 hover:text-indigo-900" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <!-- END Table -->

          <div class="px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
            <div class="flex-1 flex justify-between sm:hidden">
              <%= link_to_previous_page @checks, 'Previous page', class: "ml-3 paginate-page paginate-page-single" %>
              <%= link_to_next_page @checks, 'Next Page', class: "paginate-page paginate-page-single" %>
            </div>
            <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
              <div>
                <p class="text-sm text-gray-700 ">
                  Showing
                  <span class="font-medium"><%= @checks.offset_value + 1 %></span>
                  to
                  <span class="font-medium"><%= @checks.offset_value + (@checks.respond_to?(:records) ? @checks.records : @checks.to_a).size %></span>
                  of
                  <span class="font-medium"><%= @checks.total_count %></span>
                  results
                </p>
              </div>
              <%= paginate @checks %>
            </div>
          </div>
        <% else %>
          <div class="block w-full border-2 border-gray-300 border-dashed rounded-lg p-6 text-center">
            <p class="italic ">No results</p>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/checks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @check %>

    <%= link_to 'Edit this check', edit_check_path(@check), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this check', check_path(@check), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to checks', checks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>